#!/bin/bash
/Library/Java/JavaVirtualMachines/jdk-23.jdk/Contents/Home/bin/java \
  -Dfile.encoding=UTF-8 \
  -Dsun.stdout.encoding=UTF-8 \
  -Dsun.stderr.encoding=UTF-8 \
  -Xmx96g \
  -jar /Users/nik/IdeaProjects/Old_projects/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar \
  "$@"
