[package]
name = "doppler-rs"
version = "0.0.2"
authors = ["Nikolas Yanek-Chrones <research@icarai.io>"]
description = "Unofficial client library for the Doppler API - secure secrets management platform"
license = "MIT"
edition = "2021"
repository = "https://github.com/nikothomas/doppler-rs"
homepage = "https://github.com/nikothomas/doppler-rs"
documentation = "https://docs.rs/doppler-rs"
readme = "README.md"
keywords = ["doppler", "secrets", "api", "client", "env"]
categories = ["api-bindings", "web-programming::http-client"]

[features]
default = []
rustls = ["reqwest/rustls-tls"]

[dependencies]
serde = { version = "^1.0", features = ["derive"] }
serde_with = { version = "^3.8", default-features = false, features = ["base64", "std", "macros"] }
serde_json = "^1.0"
serde_repr = "^0.1"
url = "^2.5"
chrono = { version = "^0.4", features = ["serde"] }
reqwest = { version = "^0.12", default-features = false, features = ["json", "multipart"] }

[dev-dependencies]
tokio = { version = "^1.39.0", features = ["full"] } 