/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuditGetUser200ResponseWorkplaceUserUser {
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "profile_image_url", skip_serializing_if = "Option::is_none")]
    pub profile_image_url: Option<String>,
    #[serde(rename = "mfa_enabled", skip_serializing_if = "Option::is_none")]
    pub mfa_enabled: Option<bool>,
    #[serde(rename = "thirdparty_sso_enabled", skip_serializing_if = "Option::is_none")]
    pub thirdparty_sso_enabled: Option<bool>,
    #[serde(rename = "saml_sso_enabled", skip_serializing_if = "Option::is_none")]
    pub saml_sso_enabled: Option<bool>,
}

impl AuditGetUser200ResponseWorkplaceUserUser {
    pub fn new() -> AuditGetUser200ResponseWorkplaceUserUser {
        AuditGetUser200ResponseWorkplaceUserUser {
            email: None,
            name: None,
            username: None,
            profile_image_url: None,
            mfa_enabled: None,
            thirdparty_sso_enabled: None,
            saml_sso_enabled: None,
        }
    }
}

