/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuditGetUser200Response {
    #[serde(rename = "workplace_user", skip_serializing_if = "Option::is_none")]
    pub workplace_user: Option<models::AuditGetUser200ResponseWorkplaceUser>,
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
}

impl AuditGetUser200Response {
    pub fn new() -> AuditGetUser200Response {
        AuditGetUser200Response {
            workplace_user: None,
            success: None,
        }
    }
}

