/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthRevokeRequest {
    #[serde(rename = "token")]
    pub token: String,
}

impl AuthRevokeRequest {
    pub fn new(token: String) -> AuthRevokeRequest {
        AuthRevokeRequest {
            token,
        }
    }
}

