/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthOidcRequest {
    /// the OIDC token string from your OIDC provider (likely CI)
    #[serde(rename = "token")]
    pub token: String,
    /// Identity ID from the Doppler Dashboard
    #[serde(rename = "identity")]
    pub identity: String,
}

impl AuthOidcRequest {
    pub fn new(token: String, identity: String) -> AuthOidcRequest {
        AuthOidcRequest {
            token,
            identity,
        }
    }
}

