/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangeRequestPoliciesList200ResponsePoliciesInner {
    #[serde(rename = "policy", skip_serializing_if = "Option::is_none")]
    pub policy: Option<models::ChangeRequestPoliciesGet200ResponsePolicy>,
}

impl ChangeRequestPoliciesList200ResponsePoliciesInner {
    pub fn new() -> ChangeRequestPoliciesList200ResponsePoliciesInner {
        ChangeRequestPoliciesList200ResponsePoliciesInner {
            policy: None,
        }
    }
}

