/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangeRequestPoliciesList200Response {
    #[serde(rename = "policies", skip_serializing_if = "Option::is_none")]
    pub policies: Option<Vec<models::ChangeRequestPoliciesList200ResponsePoliciesInner>>,
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
}

impl ChangeRequestPoliciesList200Response {
    pub fn new() -> ChangeRequestPoliciesList200Response {
        ChangeRequestPoliciesList200Response {
            policies: None,
            success: None,
        }
    }
}

