/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangeRequestPoliciesUpdateRequest {
    /// The name of the policy.
    #[serde(rename = "name")]
    pub name: String,
    /// An optional description of the policy.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// A list of rules the policy enforces.
    #[serde(rename = "rules")]
    pub rules: Vec<models::ChangeRequestPoliciesUpdateRequestRulesInner>,
    #[serde(rename = "targets")]
    pub targets: models::ChangeRequestPoliciesUpdateRequestTargets,
}

impl ChangeRequestPoliciesUpdateRequest {
    pub fn new(name: String, rules: Vec<models::ChangeRequestPoliciesUpdateRequestRulesInner>, targets: models::ChangeRequestPoliciesUpdateRequestTargets) -> ChangeRequestPoliciesUpdateRequest {
        ChangeRequestPoliciesUpdateRequest {
            name,
            description: None,
            rules,
            targets,
        }
    }
}

