/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangeRequestPoliciesGet200ResponsePolicyTargets {
    #[serde(rename = "allProjects", skip_serializing_if = "Option::is_none")]
    pub all_projects: Option<bool>,
    #[serde(rename = "projects", skip_serializing_if = "Option::is_none")]
    pub projects: Option<serde_json::Value>,
}

impl ChangeRequestPoliciesGet200ResponsePolicyTargets {
    pub fn new() -> ChangeRequestPoliciesGet200ResponsePolicyTargets {
        ChangeRequestPoliciesGet200ResponsePolicyTargets {
            all_projects: None,
            projects: None,
        }
    }
}

