/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangeRequestPoliciesUpdate200Response {
    #[serde(rename = "policy", skip_serializing_if = "Option::is_none")]
    pub policy: Option<models::ChangeRequestPoliciesUpdate200ResponsePolicy>,
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
}

impl ChangeRequestPoliciesUpdate200Response {
    pub fn new() -> ChangeRequestPoliciesUpdate200Response {
        ChangeRequestPoliciesUpdate200Response {
            policy: None,
            success: None,
        }
    }
}

