/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangeRequestPoliciesUpdateRequestRulesInner {
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The number of required reviewers. Only applies to \"RequiredReviewer\" rules.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// A list of required reviewers. If specified, only reviews from reviewers in this list will satisfy the policy. Only applies to \"RequiredReviewer\" rules.
    #[serde(rename = "subjects", skip_serializing_if = "Option::is_none")]
    pub subjects: Option<Vec<models::ChangeRequestPoliciesUpdateRequestRulesInnerSubjectsInner>>,
}

impl ChangeRequestPoliciesUpdateRequestRulesInner {
    pub fn new(r#type: Type) -> ChangeRequestPoliciesUpdateRequestRulesInner {
        ChangeRequestPoliciesUpdateRequestRulesInner {
            r#type,
            count: None,
            subjects: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "\"RequiredReviewer\"")]
    DoubleQuoteRequiredReviewerDoubleQuote,
    #[serde(rename = "\"DisallowSelfReview\"")]
    DoubleQuoteDisallowSelfReviewDoubleQuote,
}

impl Default for Type {
    fn default() -> Type {
        Self::DoubleQuoteRequiredReviewerDoubleQuote
    }
}

