/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigsGet200Response {
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<models::ConfigsGet200ResponseConfig>,
}

impl ConfigsGet200Response {
    pub fn new() -> ConfigsGet200Response {
        ConfigsGet200Response {
            config: None,
        }
    }
}

