/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigLogsGet200Response {
    #[serde(rename = "log", skip_serializing_if = "Option::is_none")]
    pub log: Option<models::ConfigLogsGet200ResponseLog>,
}

impl ConfigLogsGet200Response {
    pub fn new() -> ConfigLogsGet200Response {
        ConfigLogsGet200Response {
            log: None,
        }
    }
}

