/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigsInherits200ResponseConfigInheritsInner {
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<String>,
}

impl ConfigsInherits200ResponseConfigInheritsInner {
    pub fn new() -> ConfigsInherits200ResponseConfigInheritsInner {
        ConfigsInherits200ResponseConfigInheritsInner {
            project: None,
            config: None,
        }
    }
}

