/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigsInherits200ResponseConfig {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "root", skip_serializing_if = "Option::is_none")]
    pub root: Option<bool>,
    #[serde(rename = "inheritable", skip_serializing_if = "Option::is_none")]
    pub inheritable: Option<bool>,
    #[serde(rename = "inheriting", skip_serializing_if = "Option::is_none")]
    pub inheriting: Option<bool>,
    #[serde(rename = "inherits", skip_serializing_if = "Option::is_none")]
    pub inherits: Option<Vec<models::ConfigsInherits200ResponseConfigInheritsInner>>,
    #[serde(rename = "inheritedBy", skip_serializing_if = "Option::is_none")]
    pub inherited_by: Option<Vec<serde_json::Value>>,
    #[serde(rename = "locked", skip_serializing_if = "Option::is_none")]
    pub locked: Option<bool>,
    #[serde(rename = "initial_fetch_at", skip_serializing_if = "Option::is_none")]
    pub initial_fetch_at: Option<String>,
    #[serde(rename = "last_fetch_at", skip_serializing_if = "Option::is_none")]
    pub last_fetch_at: Option<String>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "environment", skip_serializing_if = "Option::is_none")]
    pub environment: Option<String>,
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
}

impl ConfigsInherits200ResponseConfig {
    pub fn new() -> ConfigsInherits200ResponseConfig {
        ConfigsInherits200ResponseConfig {
            name: None,
            root: None,
            inheritable: None,
            inheriting: None,
            inherits: None,
            inherited_by: None,
            locked: None,
            initial_fetch_at: None,
            last_fetch_at: None,
            created_at: None,
            environment: None,
            project: None,
            slug: None,
        }
    }
}

