/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigsInheritable200Response {
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<models::ConfigsInheritable200ResponseConfig>,
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
}

impl ConfigsInheritable200Response {
    pub fn new() -> ConfigsInheritable200Response {
        ConfigsInheritable200Response {
            config: None,
            success: None,
        }
    }
}

