/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigsLock200Response {
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<models::ConfigsLock200ResponseConfig>,
}

impl ConfigsLock200Response {
    pub fn new() -> ConfigsLock200Response {
        ConfigsLock200Response {
            config: None,
        }
    }
}

