/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigLogsRollback200ResponseLogDiffInner {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "removed", skip_serializing_if = "Option::is_none")]
    pub removed: Option<String>,
}

impl ConfigLogsRollback200ResponseLogDiffInner {
    pub fn new() -> ConfigLogsRollback200ResponseLogDiffInner {
        ConfigLogsRollback200ResponseLogDiffInner {
            name: None,
            removed: None,
        }
    }
}

