/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigsCreateRequest {
    /// Unique identifier for the project object.
    #[serde(rename = "project")]
    pub project: String,
    /// Identifier for the environment object.
    #[serde(rename = "environment")]
    pub environment: String,
    /// Name of the new branch config.
    #[serde(rename = "name")]
    pub name: String,
}

impl ConfigsCreateRequest {
    pub fn new(project: String, environment: String, name: String) -> ConfigsCreateRequest {
        ConfigsCreateRequest {
            project,
            environment,
            name,
        }
    }
}

