/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnvironmentsCreateRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "slug")]
    pub slug: String,
    /// Whether or not to enable personal configs for the environment
    #[serde(rename = "personal_configs", skip_serializing_if = "Option::is_none")]
    pub personal_configs: Option<bool>,
}

impl EnvironmentsCreateRequest {
    pub fn new(name: String, slug: String) -> EnvironmentsCreateRequest {
        EnvironmentsCreateRequest {
            name,
            slug,
            personal_configs: None,
        }
    }
}

