/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnvironmentsCreate200Response {
    #[serde(rename = "environment", skip_serializing_if = "Option::is_none")]
    pub environment: Option<models::EnvironmentsList200ResponseEnvironmentsInner>,
}

impl EnvironmentsCreate200Response {
    pub fn new() -> EnvironmentsCreate200Response {
        EnvironmentsCreate200Response {
            environment: None,
        }
    }
}

