/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupsList200ResponseGroupsInner {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "default_project_role", skip_serializing_if = "Option::is_none")]
    pub default_project_role: Option<models::GroupsGet200ResponseGroupDefaultProjectRole>,
}

impl GroupsList200ResponseGroupsInner {
    pub fn new() -> GroupsList200ResponseGroupsInner {
        GroupsList200ResponseGroupsInner {
            name: None,
            slug: None,
            created_at: None,
            default_project_role: None,
        }
    }
}

