/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupsGet200ResponseGroupProjectsInner {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<models::GroupsGet200ResponseGroupProjectsInnerRole>,
}

impl GroupsGet200ResponseGroupProjectsInner {
    pub fn new() -> GroupsGet200ResponseGroupProjectsInner {
        GroupsGet200ResponseGroupProjectsInner {
            name: None,
            slug: None,
            role: None,
        }
    }
}

