/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IntegrationsGet200Response {
    #[serde(rename = "integration", skip_serializing_if = "Option::is_none")]
    pub integration: Option<models::IntegrationsGet200ResponseIntegration>,
}

impl IntegrationsGet200Response {
    pub fn new() -> IntegrationsGet200Response {
        IntegrationsGet200Response {
            integration: None,
        }
    }
}

