/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IntegrationsCreateRequest {
    /// The integration type
    #[serde(rename = "type")]
    pub r#type: String,
    /// The name of the integration
    #[serde(rename = "name")]
    pub name: String,
    /// The authentication data for the integration
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
}

impl IntegrationsCreateRequest {
    pub fn new(r#type: String, name: String) -> IntegrationsCreateRequest {
        IntegrationsCreateRequest {
            r#type,
            name,
            data: None,
        }
    }
}

