/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvitesList200ResponseInvitesInner {
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "workplace_role", skip_serializing_if = "Option::is_none")]
    pub workplace_role: Option<models::InvitesList200ResponseInvitesInnerWorkplaceRole>,
}

impl InvitesList200ResponseInvitesInner {
    pub fn new() -> InvitesList200ResponseInvitesInner {
        InvitesList200ResponseInvitesInner {
            slug: None,
            email: None,
            created_at: None,
            workplace_role: None,
        }
    }
}

