/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectMembersAdd200Response {
    #[serde(rename = "member", skip_serializing_if = "Option::is_none")]
    pub member: Option<models::ProjectMembersList200ResponseMembersInner>,
}

impl ProjectMembersAdd200Response {
    pub fn new() -> ProjectMembersAdd200Response {
        ProjectMembersAdd200Response {
            member: None,
        }
    }
}

