/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectMembersList200ResponseMembersInner {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<models::ProjectMembersList200ResponseMembersInnerRole>,
    #[serde(rename = "access_all_environments", skip_serializing_if = "Option::is_none")]
    pub access_all_environments: Option<bool>,
    #[serde(rename = "environments", skip_serializing_if = "Option::is_none")]
    pub environments: Option<Vec<String>>,
}

impl ProjectMembersList200ResponseMembersInner {
    pub fn new() -> ProjectMembersList200ResponseMembersInner {
        ProjectMembersList200ResponseMembersInner {
            r#type: None,
            slug: None,
            role: None,
            access_all_environments: None,
            environments: None,
        }
    }
}

