/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectRolesUpdate200Response {
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<models::ProjectRolesUpdate200ResponseRole>,
}

impl ProjectRolesUpdate200Response {
    pub fn new() -> ProjectRolesUpdate200Response {
        ProjectRolesUpdate200Response {
            role: None,
        }
    }
}

