/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectMembersUpdateRequest {
    /// Identifier of the project role
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    /// Environment slugs to grant the member access to
    #[serde(rename = "environments", skip_serializing_if = "Option::is_none")]
    pub environments: Option<Vec<String>>,
}

impl ProjectMembersUpdateRequest {
    pub fn new() -> ProjectMembersUpdateRequest {
        ProjectMembersUpdateRequest {
            role: None,
            environments: None,
        }
    }
}

