/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectMembersList200Response {
    #[serde(rename = "members", skip_serializing_if = "Option::is_none")]
    pub members: Option<Vec<models::ProjectMembersList200ResponseMembersInner>>,
}

impl ProjectMembersList200Response {
    pub fn new() -> ProjectMembersList200Response {
        ProjectMembersList200Response {
            members: None,
        }
    }
}

