/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectsUpdateRequest {
    /// Unique identifier for the project object.
    #[serde(rename = "project")]
    pub project: String,
    /// Name of the project.
    #[serde(rename = "name")]
    pub name: String,
    /// Description of the project.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl ProjectsUpdateRequest {
    pub fn new(project: String, name: String) -> ProjectsUpdateRequest {
        ProjectsUpdateRequest {
            project,
            name,
            description: None,
        }
    }
}

