/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectMembersList200ResponseMembersInnerRole {
    #[serde(rename = "identifier", skip_serializing_if = "Option::is_none")]
    pub identifier: Option<String>,
}

impl ProjectMembersList200ResponseMembersInnerRole {
    pub fn new() -> ProjectMembersList200ResponseMembersInnerRole {
        ProjectMembersList200ResponseMembersInnerRole {
            identifier: None,
        }
    }
}

