/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectsCreate200Response {
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<models::ProjectsCreate200ResponseProject>,
}

impl ProjectsCreate200Response {
    pub fn new() -> ProjectsCreate200Response {
        ProjectsCreate200Response {
            project: None,
        }
    }
}

