/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SecretsUpdateRequestChangeRequestsInnerValueType : The default valueType (string) will result in no validations being applied.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretsUpdateRequestChangeRequestsInnerValueType {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
}

impl SecretsUpdateRequestChangeRequestsInnerValueType {
    /// The default valueType (string) will result in no validations being applied.
    pub fn new() -> SecretsUpdateRequestChangeRequestsInnerValueType {
        SecretsUpdateRequestChangeRequestsInnerValueType {
            r#type: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "string")]
    String,
    #[serde(rename = "json")]
    Json,
    #[serde(rename = "json5")]
    Json5,
    #[serde(rename = "boolean")]
    Boolean,
    #[serde(rename = "integer")]
    Integer,
    #[serde(rename = "decimal")]
    Decimal,
    #[serde(rename = "email")]
    Email,
    #[serde(rename = "url")]
    Url,
    #[serde(rename = "uuidv4")]
    Uuidv4,
    #[serde(rename = "cuid2")]
    Cuid2,
    #[serde(rename = "ulid")]
    Ulid,
    #[serde(rename = "datetime8601")]
    Datetime8601,
    #[serde(rename = "date8601")]
    Date8601,
    #[serde(rename = "yaml")]
    Yaml,
}

impl Default for Type {
    fn default() -> Type {
        Self::String
    }
}

