/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SecretsUpdateRequestSecrets : Either `secrets` or `change_requests` is required (can't use both). Object of secrets you would like to save to the config. Try it with the sample secrets below.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretsUpdateRequestSecrets {
    #[serde(rename = "STRIPE", skip_serializing_if = "Option::is_none")]
    pub stripe: Option<String>,
    #[serde(rename = "ALGOLIA", skip_serializing_if = "Option::is_none")]
    pub algolia: Option<String>,
    #[serde(rename = "DATABASE", skip_serializing_if = "Option::is_none")]
    pub database: Option<String>,
}

impl SecretsUpdateRequestSecrets {
    /// Either `secrets` or `change_requests` is required (can't use both). Object of secrets you would like to save to the config. Try it with the sample secrets below.
    pub fn new() -> SecretsUpdateRequestSecrets {
        SecretsUpdateRequestSecrets {
            stripe: None,
            algolia: None,
            database: None,
        }
    }
}

