/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretsDownload200Response {
    #[serde(rename = "STRIPE", skip_serializing_if = "Option::is_none")]
    pub stripe: Option<String>,
    #[serde(rename = "ALGOLIA", skip_serializing_if = "Option::is_none")]
    pub algolia: Option<String>,
    #[serde(rename = "DATABASE", skip_serializing_if = "Option::is_none")]
    pub database: Option<String>,
    #[serde(rename = "USER", skip_serializing_if = "Option::is_none")]
    pub user: Option<String>,
}

impl SecretsDownload200Response {
    pub fn new() -> SecretsDownload200Response {
        SecretsDownload200Response {
            stripe: None,
            algolia: None,
            database: None,
            user: None,
        }
    }
}

