/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretsList200ResponseSecrets {
    #[serde(rename = "STRIPE", skip_serializing_if = "Option::is_none")]
    pub stripe: Option<models::SecretsList200ResponseSecretsStripe>,
    #[serde(rename = "ALGOLIA", skip_serializing_if = "Option::is_none")]
    pub algolia: Option<models::SecretsList200ResponseSecretsAlgolia>,
    #[serde(rename = "DATABASE", skip_serializing_if = "Option::is_none")]
    pub database: Option<models::SecretsList200ResponseSecretsDatabase>,
    #[serde(rename = "USER", skip_serializing_if = "Option::is_none")]
    pub user: Option<models::SecretsList200ResponseSecretsUser>,
}

impl SecretsList200ResponseSecrets {
    pub fn new() -> SecretsList200ResponseSecrets {
        SecretsList200ResponseSecrets {
            stripe: None,
            algolia: None,
            database: None,
            user: None,
        }
    }
}

