/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretsUpdate200ResponseSecrets {
    #[serde(rename = "STRIPE", skip_serializing_if = "Option::is_none")]
    pub stripe: Option<models::SecretsUpdate200ResponseSecretsStripe>,
    #[serde(rename = "ALGOLIA", skip_serializing_if = "Option::is_none")]
    pub algolia: Option<models::SecretsUpdate200ResponseSecretsAlgolia>,
    #[serde(rename = "DATABASE", skip_serializing_if = "Option::is_none")]
    pub database: Option<models::SecretsUpdate200ResponseSecretsDatabase>,
}

impl SecretsUpdate200ResponseSecrets {
    pub fn new() -> SecretsUpdate200ResponseSecrets {
        SecretsUpdate200ResponseSecrets {
            stripe: None,
            algolia: None,
            database: None,
        }
    }
}

