/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretsList200ResponseSecretsAlgolia {
    #[serde(rename = "raw", skip_serializing_if = "Option::is_none")]
    pub raw: Option<String>,
    #[serde(rename = "computed", skip_serializing_if = "Option::is_none")]
    pub computed: Option<String>,
    #[serde(rename = "note", skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    #[serde(rename = "rawVisibility", skip_serializing_if = "Option::is_none")]
    pub raw_visibility: Option<String>,
    #[serde(rename = "computedVisibility", skip_serializing_if = "Option::is_none")]
    pub computed_visibility: Option<String>,
}

impl SecretsList200ResponseSecretsAlgolia {
    pub fn new() -> SecretsList200ResponseSecretsAlgolia {
        SecretsList200ResponseSecretsAlgolia {
            raw: None,
            computed: None,
            note: None,
            raw_visibility: None,
            computed_visibility: None,
        }
    }
}

