/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretsUpdate200Response {
    #[serde(rename = "secrets", skip_serializing_if = "Option::is_none")]
    pub secrets: Option<models::SecretsUpdate200ResponseSecrets>,
}

impl SecretsUpdate200Response {
    pub fn new() -> SecretsUpdate200Response {
        SecretsUpdate200Response {
            secrets: None,
        }
    }
}

