/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceTokensList200Response {
    #[serde(rename = "tokens", skip_serializing_if = "Option::is_none")]
    pub tokens: Option<Vec<models::ServiceTokensList200ResponseTokensInner>>,
}

impl ServiceTokensList200Response {
    pub fn new() -> ServiceTokensList200Response {
        ServiceTokensList200Response {
            tokens: None,
        }
    }
}

