/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceAccountTokensCreateRequest {
    /// The display name of the API token
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The datetime at which the API token should expire. If not provided, the API token will remain vaild indefinitely unless manually revoked
    #[serde(rename = "expires_at", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
}

impl ServiceAccountTokensCreateRequest {
    pub fn new() -> ServiceAccountTokensCreateRequest {
        ServiceAccountTokensCreateRequest {
            name: None,
            expires_at: None,
        }
    }
}

