/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceAccountsUpdate200Response {
    #[serde(rename = "service_account", skip_serializing_if = "Option::is_none")]
    pub service_account: Option<models::ServiceAccountsUpdate200ResponseServiceAccount>,
}

impl ServiceAccountsUpdate200Response {
    pub fn new() -> ServiceAccountsUpdate200Response {
        ServiceAccountsUpdate200Response {
            service_account: None,
        }
    }
}

