/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceAccountTokensList200Response {
    #[serde(rename = "api_tokens", skip_serializing_if = "Option::is_none")]
    pub api_tokens: Option<Vec<models::ServiceAccountTokensList200ResponseApiTokensInner>>,
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
}

impl ServiceAccountTokensList200Response {
    pub fn new() -> ServiceAccountTokensList200Response {
        ServiceAccountTokensList200Response {
            api_tokens: None,
            success: None,
        }
    }
}

