/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceAccountTokensGet200Response {
    #[serde(rename = "api_token", skip_serializing_if = "Option::is_none")]
    pub api_token: Option<models::ServiceAccountTokensGet200ResponseApiToken>,
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
}

impl ServiceAccountTokensGet200Response {
    pub fn new() -> ServiceAccountTokensGet200Response {
        ServiceAccountTokensGet200Response {
            api_token: None,
            success: None,
        }
    }
}

