/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceAccountsList200Response {
    #[serde(rename = "service_accounts", skip_serializing_if = "Option::is_none")]
    pub service_accounts: Option<Vec<models::ServiceAccountsGet200ResponseServiceAccount>>,
}

impl ServiceAccountsList200Response {
    pub fn new() -> ServiceAccountsList200Response {
        ServiceAccountsList200Response {
            service_accounts: None,
        }
    }
}

