/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceAccountsUpdate200ResponseServiceAccountWorkplaceRole {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "permissions", skip_serializing_if = "Option::is_none")]
    pub permissions: Option<Vec<serde_json::Value>>,
    #[serde(rename = "identifier", skip_serializing_if = "Option::is_none")]
    pub identifier: Option<String>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "is_custom_role", skip_serializing_if = "Option::is_none")]
    pub is_custom_role: Option<bool>,
    #[serde(rename = "is_inline_role", skip_serializing_if = "Option::is_none")]
    pub is_inline_role: Option<bool>,
}

impl ServiceAccountsUpdate200ResponseServiceAccountWorkplaceRole {
    pub fn new() -> ServiceAccountsUpdate200ResponseServiceAccountWorkplaceRole {
        ServiceAccountsUpdate200ResponseServiceAccountWorkplaceRole {
            name: None,
            permissions: None,
            identifier: None,
            created_at: None,
            is_custom_role: None,
            is_inline_role: None,
        }
    }
}

