/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncsCreate200Response {
    #[serde(rename = "sync", skip_serializing_if = "Option::is_none")]
    pub sync: Option<models::SyncsCreate200ResponseSync>,
}

impl SyncsCreate200Response {
    pub fn new() -> SyncsCreate200Response {
        SyncsCreate200Response {
            sync: None,
        }
    }
}

