/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncsCreateRequest {
    /// The integration slug which the sync will use
    #[serde(rename = "integration")]
    pub integration: String,
    /// Configuration data for the sync
    #[serde(rename = "data")]
    pub data: serde_json::Value,
    /// An option indicating if and how Doppler should attempt to import secrets from the sync destination
    #[serde(rename = "import_option", skip_serializing_if = "Option::is_none")]
    pub import_option: Option<ImportOption>,
    /// Causes sync creation to wait for the initial sync to complete before returning.
    #[serde(rename = "await_initial_sync", skip_serializing_if = "Option::is_none")]
    pub await_initial_sync: Option<bool>,
}

impl SyncsCreateRequest {
    pub fn new(integration: String, data: serde_json::Value) -> SyncsCreateRequest {
        SyncsCreateRequest {
            integration,
            data,
            import_option: None,
            await_initial_sync: None,
        }
    }
}
/// An option indicating if and how Doppler should attempt to import secrets from the sync destination
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ImportOption {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "prefer_doppler")]
    PreferDoppler,
    #[serde(rename = "prefer_integration")]
    PreferIntegration,
}

impl Default for ImportOption {
    fn default() -> ImportOption {
        Self::None
    }
}

