/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsersList200Response {
    #[serde(rename = "workplace_users", skip_serializing_if = "Option::is_none")]
    pub workplace_users: Option<Vec<models::UsersList200ResponseWorkplaceUsersInner>>,
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<i32>,
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
}

impl UsersList200Response {
    pub fn new() -> UsersList200Response {
        UsersList200Response {
            workplace_users: None,
            page: None,
            success: None,
        }
    }
}

