/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsersUpdateRequest {
    /// The identifier of the workplace role. E.g., `owner`, `collaborator`, etc.
    #[serde(rename = "access", skip_serializing_if = "Option::is_none")]
    pub access: Option<String>,
}

impl UsersUpdateRequest {
    pub fn new() -> UsersUpdateRequest {
        UsersUpdateRequest {
            access: None,
        }
    }
}

