/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsersList200ResponseWorkplaceUsersInner {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "access", skip_serializing_if = "Option::is_none")]
    pub access: Option<String>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<models::UsersList200ResponseWorkplaceUsersInnerUser>,
}

impl UsersList200ResponseWorkplaceUsersInner {
    pub fn new() -> UsersList200ResponseWorkplaceUsersInner {
        UsersList200ResponseWorkplaceUsersInner {
            id: None,
            access: None,
            created_at: None,
            user: None,
        }
    }
}

