/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkplaceUpdateRequest {
    /// Workplace name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "billing_email", skip_serializing_if = "Option::is_none")]
    pub billing_email: Option<String>,
    #[serde(rename = "security_email", skip_serializing_if = "Option::is_none")]
    pub security_email: Option<String>,
}

impl WorkplaceUpdateRequest {
    pub fn new() -> WorkplaceUpdateRequest {
        WorkplaceUpdateRequest {
            name: None,
            billing_email: None,
            security_email: None,
        }
    }
}

