/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkplaceGet200Response {
    #[serde(rename = "workplace", skip_serializing_if = "Option::is_none")]
    pub workplace: Option<models::WorkplaceGet200ResponseWorkplace>,
}

impl WorkplaceGet200Response {
    pub fn new() -> WorkplaceGet200Response {
        WorkplaceGet200Response {
            workplace: None,
        }
    }
}

