/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkplaceRolesGet200Response {
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<models::WorkplaceRolesList200ResponseRolesInner>,
}

impl WorkplaceRolesGet200Response {
    pub fn new() -> WorkplaceRolesGet200Response {
        WorkplaceRolesGet200Response {
            role: None,
        }
    }
}

